config/routes.rb
Rails.application.routes.draw do
  resources :relatories
  resources :managers
  root to: "managers#new"










end

app/models/manager.rb
class Manager < ActiveRecord::Base
	mount_uploader :file_txt, FileTxtUploader
	has_many :relatories,dependent: :destroy


	def importa_arquivo_bd(arquivo)
		arquivo.gsub!(/\r\n?/, "\n")
		lista_cheia = [] #lista que contem o arquivo sem os tabs

		arquivo.each_line do |line|
		  #lista = line.split(/\t+/)
		  lista_cheia.push(line.split(/\t+/)) #percorre as linhas e tira os tabs
		end
		lista_cheia.delete_at(0) #deletei a primeira linha do arquivo que tem os campos(Comprador,descrição,Preço Uniário,Quantidade,Endereço,Fornecedor)
		count = 0 #contador para saber onde comeca e termina um usuario
		lista_pra_inserir = [] #lista que contem cada usuario em um lista com todos seus dados
		lista_cheia.each do |ls|
			lista_individual = []  #lista para inserir na lista_pra_inserir,essa contem um usuarios especifico
		  	for i in 0..lista_cheia.size+1
				lista_individual.push(ls[i])
		  	end
		  	lista_pra_inserir.push(lista_individual)
			count = count +1
		end
		lista_pra_inserir.each do |novo|
			
			Relatory.create(buyer: novo[0],description: novo[1],price: novo[2],quantity: novo[3],address: novo[4],owner: novo[5],manager_id: self.id)
		end 
		
	end




end

app/models/relatory.rb
class Relatory < ActiveRecord::Base
	belongs_to :manager
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        #Aqui a magic acontece....#############
        @manager.importa_arquivo_bd(File.read params[:manager][:file_txt].path)

        format.html { redirect_to @manager, notice: 'Arquivo Salvo' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Arquivo atualizado.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Arquivo destroído.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.fetch(:manager).permit(:file_txt)
    end
end

app/controllers/relatories_controller.rb
class RelatoriesController < ApplicationController
  before_action :set_relatory, only: [:show, :edit, :update, :destroy]

  # GET /relatories
  # GET /relatories.json
  def index
    @relatories = Relatory.all
  end

  # GET /relatories/1
  # GET /relatories/1.json
  def show
  end

  # GET /relatories/new
  def new
    @relatory = Relatory.new
  end

  # GET /relatories/1/edit
  def edit
  end

  # POST /relatories
  # POST /relatories.json
  def create
    @relatory = Relatory.new(relatory_params)

    respond_to do |format|
      if @relatory.save
        format.html { redirect_to @relatory, notice: 'Relatório Salvo.' }
        format.json { render :show, status: :created, location: @relatory }
      else
        format.html { render :new }
        format.json { render json: @relatory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relatories/1
  # PATCH/PUT /relatories/1.json
  def update
    respond_to do |format|
      if @relatory.update(relatory_params)
        format.html { redirect_to @relatory, notice: 'Relatório atualizado.' }
        format.json { render :show, status: :ok, location: @relatory }
      else
        format.html { render :edit }
        format.json { render json: @relatory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relatories/1
  # DELETE /relatories/1.json
  def destroy
    @relatory.destroy
    respond_to do |format|
      format.html { redirect_to relatories_url, notice: 'Relatório deletado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relatory
      @relatory = Relatory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relatory_params
      params.require(:relatory).permit(:buyer, :description, :price,:quantity, :address, :owner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UploadXD</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"/>
  <%= favicon_link_tag 'txt-icon', :rel => 'shortcut icon' %>
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			    <%= link_to root_path,class: "navbar-brand" do %>
			        UploadXD
			    <% end %>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item active">
		        <%= link_to relatories_path,class: "nav-link" do %>
		        <span>Relatorios</span>
			    <% end %>
		      </li>

		      <li class="nav-item active">
		        <%= link_to managers_path,class: "nav-link" do %>
		        <span>Lista de Arquivos</span>
			    <% end %>
		      </li>
		    </ul>
		  </div>
		  
		</nav>

		<br></br>
	    <div class="container-fluid">

	  		<%= yield %>
	  		
	  	</div>
	</div>

</body>
</html>

app/views/managers/_form.html.erb
<%= form_for(@manager) do |f| %>
  <% if @manager.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <ul>
      <% @manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.file_field :file_txt,required: true,class: "form-control-file",id: "customFile"%>
  </div>

  <div class="actions">
    <%= f.button :submit , class: "btn btn-success btn-sm" %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h3>Editando arquivo</h3>

<%= render 'form' %>
<br>
<%= link_to 'Mostrar', @manager ,class: "btn btn-warning btn-sm"%> |
<%= link_to 'Voltar', managers_path ,class: "btn btn-primary btn-sm"%>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Listagem de arquivos</h3>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th Arquivo></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= link_to "arquivo", manager.file_txt.url %></td>
        <td><%= link_to 'Show', manager ,class: "btn btn-success btn-sm"%></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) ,class: "btn btn-warning btn-sm"%></td>
        <td><%= link_to 'Destroy', manager,class: "btn btn-danger btn-sm" ,method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo arquivo', new_manager_path ,class: "btn btn-primary btn-sm"%>

app/views/managers/new.html.erb
<h4>Faça o upload do arquivo</h4>

<%= render 'form' %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
	<%= link_to("Arquivo",@manager.file_txt.url) %>
	<br>
	<%= link_to 'Editar',edit_manager_path(@manager),class: "btn btn-info btn-sm"  %> |
	<%= link_to 'Voltar' ,managers_path ,class: "btn btn-primary btn-sm" %>
</div>

app/views/relatories/_form.html.erb
<%= form_for(@relatory) do |f| %>
  <% if @relatory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relatory.errors.count, "error") %> prohibited this relatory from being saved:</h2>

      <ul>
      <% @relatory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buyer %><br>
    <%= f.text_field :buyer %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relatories/edit.html.erb
<h1>Editing Relatory</h1>

<%= render 'form' %>

<%= link_to 'Show', @relatory %> |
<%= link_to 'Back', relatories_path %>

app/views/relatories/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listando dados upados pelos txt(s)</h3>
<br>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Comprador</th>
      <th scope="col">Descrição</th>
      <th scope="col">Preço Unitário</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Endereço</th>
      <th scope="col">Fornecedor</th>
      <th scope="col">Total da linha</th>
      <th scope="col">#</th>

    </tr>
  </thead>

  <tbody>
    <% @relatories.each do |relatory| %>
      <tr>
        <td><%= relatory.buyer %></td>
        <td><%= relatory.description %></td>
        <td><%= relatory.price %></td>
        <td><%= relatory.quantity %></td>
        <td><%= relatory.address %></td>
        <td><%= relatory.owner %></td>
        <td><%= relatory.price*relatory.quantity %></td>
        <td><%= link_to 'Mostrar', relatory ,class: "btn btn-primary btn-sm" %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/relatories/new.html.erb
<h1>New Relatory</h1>

<%= render 'form' %>

<%= link_to 'Back', relatories_path %>

app/views/relatories/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card text-center">
  <div class="card-header">
    Comprador: <%= @relatory.buyer %> / Fornecedor: <%= @relatory.owner %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @relatory.description %></h5>
    <p class="card-text">Preço: <%= @relatory.price %>/Quantidade: <%= @relatory.quantity %></p>
  </div>
  <div class="card-footer text-muted">
    Endereço: <%= @relatory.address %>
  </div>
</div>
<br>
<%= link_to 'Voltar', relatories_path ,class: "btn btn-success btn-sm" %>